<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Fterm.UI</RootNamespace>
    <AssemblyName>Fterm.UI</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.6" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.6" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.6" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.6" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Fterm.Core\Fterm.Core.csproj" />
    <ProjectReference Include="..\Fterm.Terminal\Fterm.Terminal.csproj" />
    <ProjectReference Include="..\Fterm.Protocols.Ssh\Fterm.Protocols.Ssh.csproj" />
  </ItemGroup>
</Project>
